<?php
require_once __DIR__ . '/../lib/supabase.php';
$page = $_GET['page'] ?? 'login';
$profile = flux_profile();
$transactions = flux_transactions((string) $profile['id']);
$stats = flux_dashboard_stats($transactions);
$upiId = flux_env('FLUX_PAY_UPI_ID', 'BHARATPE2POVOR1J8D29917@unitype');
$amount = (float) ($_POST['amount'] ?? $_GET['amount'] ?? 500);
$utr = trim((string) ($_POST['utr'] ?? ''));
$fundSaved = false;
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $page === 'funds' && $utr !== '') {
    $fundSaved = flux_create_fund_request((string) $profile['id'], $amount, $utr);
}
function nav_url(string $page, array $params = []): string { return '?' . http_build_query(['page' => $page] + $params); }
function h(?string $value): string { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); }
function layout_start(string $title, string $class = ''): void { ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Flux Pay | <?= h($title) ?></title><link rel="stylesheet" href="styles.css"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"></head><body><main class="app <?= h($class) ?>">
<?php }
function topbar(string $title): void { ?><header class="topbar"><a class="icon-btn" href="<?= nav_url('dashboard') ?>">☰</a><h1><?= h($title) ?></h1><a class="icon-btn" href="<?= nav_url('api') ?>">◐</a><a class="logo-chip" href="<?= nav_url('profile') ?>">FLUX<br>PAY</a></header><?php }
function auth_hero(string $active = ''): void { ?><section class="hero"><div class="brand"><div class="brand-mark">ϟ</div><div><h2>Flux Pay</h2><p>PAYMENT GATEWAY</p></div></div><?php if ($active): ?><div class="stepper"><div class="step <?= $active === 'personal' ? 'active' : 'done' ?>"><span><?= $active === 'personal' ? '1' : '✓' ?></span><span>Personal</span></div><i></i><div class="step <?= $active === 'security' ? 'active' : ($active === 'confirm' ? 'done' : '') ?>"><span><?= $active === 'confirm' ? '✓' : '2' ?></span><span>Security</span></div><i></i><div class="step <?= $active === 'confirm' ? 'active' : '' ?>"><span>3</span><span>Confirm</span></div></div><?php endif; ?></section><?php }
function field(string $label, string $icon, string $name, string $placeholder, string $type = 'text'): void { ?><div class="field"><label><?= h($label) ?></label><div class="input-wrap"><span><?= $icon ?></span><input name="<?= h($name) ?>" type="<?= h($type) ?>" placeholder="<?= h($placeholder) ?>" <?= $name === 'phone' ? 'pattern="[0-9]{10}"' : '' ?>></div></div><?php }

if ($page === 'dashboard'):
layout_start('Dashboard', 'dashboard-bg'); topbar('Dashboard'); ?>
<section class="dash-intro"><p>OVERVIEW</p><h2>Your <span style="color:#287cf4">Dashboard</span></h2></section>
<section class="balance"><div class="cap"><span>▣ AVAILABLE BALANCE</span><span class="premium">♛ Premium</span></div><div class="amount"><?= flux_money((float) $profile['balance']) ?></div><div class="info-grid"><div class="info-box"><b>PHONE</b>☎ <?= h(flux_mask_phone((string) $profile['phone'])) ?></div><div class="info-box"><b>EMAIL</b>✉ <?= h(flux_mask_email((string) $profile['email'])) ?></div><div class="info-box"><b>ACCOUNT</b>🛡 <?= $profile['is_verified'] ? 'Verified' : 'Pending' ?></div><div class="info-box"><b>MEMBER SINCE</b>▣ <?= h(flux_date((string) $profile['joined_at'])) ?></div></div></section>
<section class="stats"><a class="stat" href="<?= nav_url('receipt') ?>"><div class="mini-icon">↗</div><strong>₹<?= number_format($stats['credit'], 0) ?></strong><span>Total Credit</span></a><div class="stat"><div class="mini-icon">✓</div><strong><?= $stats['success'] ?></strong><span>Successful</span></div><div class="stat"><div class="mini-icon">▤</div><strong><?= $stats['total'] ?></strong><span>Total Txns</span></div><div class="stat"><div class="mini-icon">%</div><strong><?= $stats['rate'] ?>%</strong><span>Success Rate</span></div></section>
<nav class="mobile-nav"></nav></main></body></html>
<?php elseif ($page === 'register' || $page === 'confirm'):
$confirm = $page === 'confirm'; layout_start('Register'); topbar('Register'); auth_hero($confirm ? 'confirm' : 'personal'); ?>
<section class="register-card card"><?php if (!$confirm): ?><div class="mini-icon">👤</div><h2 class="section-title">Create Account</h2><p class="subtitle">Enter your personal details below</p><form action="<?= nav_url('confirm') ?>" method="post"><?php field('FULL NAME','●','name','Enter your full name'); field('EMAIL ADDRESS','✉','email','your@email.com','email'); field('PHONE NUMBER','▯','phone','10-digit mobile number','tel'); ?><button class="btn">Continue →</button></form><div class="divider">OR</div><p style="text-align:center;color:#9aa6b8;font-size:18px">Already have an account? <a href="<?= nav_url('login') ?>">Sign In →</a></p><div class="trust"><span>● Systems Online</span><span>🛡 SSL Secured</span><span>🔒 256-bit Encrypted</span></div><?php else: $name=$_POST['name']??'Subhajit Maity'; $email=$_POST['email']??'subhajitmity04@gmail.com'; $phone=$_POST['phone']??'8637083186'; ?><div class="mini-icon">✓</div><h2 class="section-title">Review Details</h2><p class="subtitle">Confirm your information before submitting</p><div class="kv"><small>NAME</small><strong><?= h($name) ?></strong><hr><small>EMAIL</small><strong><?= h($email) ?></strong><hr><small>PHONE</small><strong><?= h($phone) ?></strong></div><div class="notice" style="background:#eef4ff;color:#334257;border-color:#d8e4ff"><span class="check" style="display:inline-grid;margin-right:12px">✓</span>I agree to the <a>Terms of Service</a> and <a>Privacy Policy</a>. I understand that Flux Pay uses bank-level security to protect my data.</div><div class="actions"><a class="btn secondary" href="<?= nav_url('register') ?>">← Back</a><a class="btn" href="<?= nav_url('dashboard') ?>">👥 Create Account</a></div><div class="divider">OR</div><p style="text-align:center;color:#9aa6b8;font-size:18px">Already registered? <a href="<?= nav_url('login') ?>">Sign In →</a></p><?php endif; ?></section><nav class="mobile-nav"></nav></main></body></html>
<?php elseif ($page === 'api'):
layout_start('API Integration'); topbar('API Integration'); $apiUrl = (isset($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'flux-pay.local') . '/api/pay.php?token=' . $profile['api_token'] . '&key=' . $profile['api_key'] . '&paytoNumber={number}&amount={amount}&comment={comment}'; ?>
<section class="page-pad"><div class="panel card"><div class="panel-head"><div class="mini-icon" style="margin:0">🔌</div><div><h2>API Status</h2><p style="color:var(--green);font-weight:900">● API is Active</p><p>Your API endpoints are live and accepting requests</p></div><div class="switch"></div></div><div class="row"><span>Total API Calls</span><strong><?= (int) $profile['api_calls'] ?></strong></div><br><div class="row"><span>Last Used</span><strong style="color:#2d75e7"><?= h($profile['api_last_used'] ? flux_date($profile['api_last_used']) : 'Never') ?></strong></div></div><div class="panel card"><div class="panel-head"><div><h2>API Credentials</h2><p>Keep these credentials secure. Do not share them publicly.</p></div></div><div class="credential"><span>🌀</span><div class="code"><?= h((string) $profile['api_token']) ?></div><button class="btn copy" data-copy="<?= h((string) $profile['api_token']) ?>">▣ Copy</button></div><div class="credential"><span>🔑</span><div class="code"><?= h((string) $profile['api_key']) ?></div><button class="btn copy" data-copy="<?= h((string) $profile['api_key']) ?>">▣ Copy</button></div><div class="notice">⚠️ <b>Security Notice</b><br>Your API credentials provide full access to your account. Keep them secure and never expose them in client-side code or public repositories.</div></div><div class="panel card"><div class="panel-head"><div><h2>API Endpoint</h2><p>Use this URL to make payment requests</p></div></div><div class="api-url"><?= h($apiUrl) ?></div><button class="btn" data-copy="<?= h($apiUrl) ?>" style="margin:22px auto 0;width:auto">▣ Copy URL</button><div class="form-panel"><h2>🧪 Test API Request</h2><?php field('paytoNumber','', 'paytoNumber','9876543210'); field('amount','', 'amount','500','number'); field('comment','', 'comment','Test payment'); ?><a class="btn" href="<?= nav_url('receipt') ?>">➤ Test API Call</a><button class="btn" style="background:#1b273b;margin-top:12px">〉_ cURL Command</button></div><h2>▣ Required Parameters</h2><div class="table-hint"><span>PARAMETER</span><span>TYPE</span><span>REQUIRED</span></div></div></section><script src="app.js"></script><nav class="mobile-nav"></nav></main></body></html>
<?php elseif ($page === 'profile'):
layout_start('Profile Settings'); topbar('Profile Settings'); ?>
<section class="profile-hero"><div class="avatar">FLUX<br>PAY</div><h2><?= h((string) $profile['full_name']) ?> ✎</h2><div class="pill">▣ Joined <?= h(flux_date((string) $profile['joined_at'])) ?></div></section><section class="profile-cards"><div class="profile-card card"><div class="mini-icon">☎</div><small>CONTACT</small><h2><?= h((string) $profile['phone']) ?></h2></div><div class="profile-card card"><div class="mini-icon">✉</div><small>EMAIL</small><h2><?= h((string) $profile['email']) ?></h2></div><div class="notice" style="background:#fff;border-style:dashed;color:#647083;text-align:center">Updating Phone or Email? <a>Contact Support</a> for manual verification.</div></section><nav class="mobile-nav"></nav></main></body></html>
<?php elseif ($page === 'funds'):
$step = $_GET['step'] ?? '1'; layout_start('Add Funds'); ?><section class="fund-title"><h2>Add Funds to Your Wallet</h2><p>Secure, instant deposits via UPI</p></section><section class="fund-card card"><div class="progress"><div class="prog <?= $step==='1'?'active':'done' ?>"><b>1</b>Enter Amount</div><div class="prog <?= $step==='2'?'active':($step==='3'?'done':'') ?>"><b>2</b>Make Payment</div><div class="prog <?= $step==='3'?'active':'' ?>"><b>3</b>Confirm UTR</div></div><?php if ($step==='1'): ?><form><input type="hidden" name="page" value="funds"><input type="hidden" name="step" value="2"><div class="field"><label>Enter Amount (₹)</label><div class="input-wrap"><b>Rs</b><input name="amount" value="500" type="number" min="20" max="100000"></div></div><div class="amount-buttons"><div class="choice">₹100</div><div class="choice">₹250</div><div class="choice active">₹500</div><div class="choice">₹1,000</div><div class="choice">₹2,000</div><div class="choice">₹5,000</div></div><p>ℹ Min: ₹20 | Max: ₹100,000</p><p><b>NOTE-</b> 2.00% service charge will be applied on the amount payed.</p><div class="manual"><h3>🏦 Manual Payment</h3><p>Use these details for manual payment:</p><div class="upi">UPI ID:<br><?= h($upiId) ?></div></div><button class="btn">Continue →</button></form><?php elseif($step==='2'): ?><h2 style="text-align:center">Scan to Pay</h2><p style="text-align:center;color:#647083">Open any UPI app and scan</p><div class="qr"></div><h2 style="text-align:center">Amount: ₹<?= number_format($amount,0) ?></h2><div class="manual"><h3>🏦 Manual Payment</h3><p>Use these details for manual payment:</p><div class="upi">UPI ID:<br><?= h($upiId) ?></div></div><a class="btn" href="<?= nav_url('funds',['step'=>'3','amount'=>$amount]) ?>">I Paid, Continue →</a><?php else: ?><form method="post" action="<?= nav_url('funds',['step'=>'3','amount'=>$amount]) ?>"><input type="hidden" name="amount" value="<?= h((string)$amount) ?>"><h2>Enter UTR/Transaction ID</h2><p>💡 Find UTR in your bank/UPI app</p><?php field('', '▤', 'utr', 'E.g.: 832617429012345'); ?><div class="manual"><h3>🏦 Manual Payment</h3><p>Use these details for manual payment:</p><div class="upi">UPI ID:<br><?= h($upiId) ?></div></div><?php if($utr): ?><p class="notice" style="background:#e7fff5;color:#08765a">Submitted<?= $fundSaved ? ' to Supabase' : ' in demo mode' ?>.</p><?php endif; ?><div class="actions"><a class="btn secondary" href="<?= nav_url('funds',['step'=>'2','amount'=>$amount]) ?>">← Back</a><button class="btn green">✓ Submit</button></div></form><?php endif; ?></section><nav class="mobile-nav"></nav></main></body></html>
<?php elseif ($page === 'receipt'):
$tx = $transactions[0]; layout_start('Receipt'); ?><section class="receipt-overlay"><article class="receipt"><h2><?= h($tx['title'] ?? 'Payment to Mk (223••••••41)') ?></h2><p style="color:#8a96a8"><?= h(date('d M Y, h:i A', strtotime((string)($tx['created_at'] ?? 'now')))) ?></p><div class="red"><?= ($tx['amount'] ?? 0) < 0 ? '-' : '' ?>₹<?= number_format(abs((float)($tx['amount'] ?? 0)),2) ?></div><p style="text-align:center"><span class="badge">✓ Success</span></p><?php foreach ([['TRANSACTION ID',$tx['id']??'STG-17802380454464ZBSY-D'],['PAYMENT METHOD','↔ '.($tx['method']??'Transfer')],['CATEGORY',$tx['category']??'transfer'],['NET BALANCE AFTER',flux_money((float)($tx['net_balance_after']??0))],['NOTES',$tx['notes']??'Single payment sent'],['COMMENT',$tx['comment']??'Single Payment']] as $item): ?><div class="kv"><small><?= h($item[0]) ?></small><strong><?= h((string)$item[1]) ?></strong></div><?php endforeach; ?><button class="btn">▤ Download Receipt</button><a class="btn secondary" style="margin-top:14px" href="<?= nav_url('dashboard') ?>">× Close</a></article></section></main></body></html>
<?php else:
layout_start('Login'); topbar('Login'); auth_hero(); ?>
<section class="auth-card card"><div class="mini-icon">↪</div><h2 class="section-title">Sign In</h2><p class="subtitle">Enter your credentials to continue</p><form action="<?= nav_url('dashboard') ?>" method="post"><?php field('PHONE NUMBER','▯','phone','10-digit phone number','tel'); field('PASSWORD','⚿','password','Enter your password','password'); ?><div class="row"><label class="remember"><span class="check">✓</span>Remember me</label><a>Forgot password?</a></div><br><button class="btn">↪ Sign In</button></form><div class="divider">OR</div><p style="text-align:center;color:#9aa6b8;font-size:18px">No account? <a href="<?= nav_url('register') ?>">Create one →</a></p></section><nav class="mobile-nav"></nav></main></body></html>
<?php endif; ?>
